<a href="https://colab.research.google.com/github/Taofeeq97/KNN-classification-model/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [68]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [70]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [72]:
df.dropna(how='any', inplace=True)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [74]:
df.Churn.value_counts()

Churn
No     5163
Yes    1869
Name: count, dtype: int64

In [75]:
X = df.drop(['customerID', 'Churn'], axis=1)

In [76]:
y=df.Churn.values

In [77]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

#Convert categorical X variables to numerical to be able to plug it into ML model ---> Feature Encoding

In [78]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [79]:
X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True, dtype=int)

In [82]:
X

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,tenure_2,tenure_3,tenure_4,tenure_5,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,29.85,29.85,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,0,56.95,1889.50,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,53.85,108.15,1,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,1
3,0,42.30,1840.75,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,70.70,151.65,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,84.80,1990.50,1,1,1,0,0,0,0,...,0,1,0,1,1,0,1,0,0,1
7039,0,103.20,7362.90,0,1,1,0,0,0,0,...,0,1,0,1,1,0,1,1,0,0
7040,0,29.60,346.45,0,1,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
7041,1,74.40,306.60,1,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
7042,0,105.65,6844.50,1,0,0,0,0,0,0,...,0,1,0,1,0,1,1,0,0,0

#Splitting to train and test

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [85]:
len(x_train)

5274

In [86]:
x_train.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,tenure_2,tenure_3,tenure_4,tenure_5,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
3166,0,48.80,664.40,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4333,0,90.55,2929.75,1,1,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
1927,0,107.35,5118.95,1,1,1,0,0,0,0,...,0,1,0,1,0,0,1,0,0,0
2315,0,73.45,2661.10,1,1,1,0,0,0,0,...,0,1,0,1,1,0,1,0,0,0
858,0,89.00,5898.60,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

Features scaling

In [87]:
x_test.head(1)

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,tenure_2,tenure_3,tenure_4,tenure_5,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
2481,1,25.0,1501.75,1,1,0,0,0,0,0,...,1,0,1,0,0,1,0,0,0,0

In [89]:
x_test.columns

Index(['SeniorCitizen', 'MonthlyCharges', 'TotalCharges', 'gender_Male',
       'Partner_Yes', 'Dependents_Yes', 'tenure_2', 'tenure_3', 'tenure_4',
       'tenure_5', 'tenure_6', 'tenure_7', 'tenure_8', 'tenure_9', 'tenure_10',
       'tenure_11', 'tenure_12', 'tenure_13', 'tenure_14', 'tenure_15',
       'tenure_16', 'tenure_17', 'tenure_18', 'tenure_19', 'tenure_20',
       'tenure_21', 'tenure_22', 'tenure_23', 'tenure_24', 'tenure_25',
       'tenure_26', 'tenure_27', 'tenure_28', 'tenure_29', 'tenure_30',
       'tenure_31', 'tenure_32', 'tenure_33', 'tenure_34', 'tenure_35',
       'tenure_36', 'tenure_37', 'tenure_38', 'tenure_39', 'tenure_40',
       'tenure_41', 'tenure_42', 'tenure_43', 'tenure_44', 'tenure_45',
       'tenure_46', 'tenure_47', 'tenure_48', 'tenure_49', 'tenure_50',
       'tenure_51', 'tenure_52', 'tenure_53', 'tenure_54', 'tenure_55',
       'tenure_56', 'tenure_57', 'tenure_58', 'tenure_59', 'tenure_60',
       'tenure_61', 'tenure_62', 'tenure_63', 'tenure_64', 'tenure_65',
       'tenure_66', 'tenure_67', 'tenure_68', 'tenure_69', 'tenure_70',
       'tenure_71', 'tenure_72', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [60]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [61]:
x_train

array([[-0.4377158 , -0.52638   , -0.71215437, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [-0.4377158 ,  0.85826225,  0.29030505, ...,  1.88322907,
        -0.71708569, -0.54360352],
       [-0.4377158 ,  1.41543565,  1.25906669, ..., -0.53100285,
        -0.71708569, -0.54360352],
       ...,
       [-0.4377158 ,  0.54651046, -0.65903002, ..., -0.53100285,
         1.39453348, -0.54360352],
       [-0.4377158 , -1.48982568, -0.56849072, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [ 2.28458741,  0.29777233, -0.35853779, ..., -0.53100285,
         1.39453348, -0.54360352]])

#KNN Classifier

In [62]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)
y_pred

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

In [63]:
y_test

array(['No', 'No', 'Yes', ..., 'Yes', 'No', 'No'], dtype=object)

# Model classification performance metrics

In [64]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
accuracy_score(y_test, y_pred)

0.7684869169510807

##New data prediction

In [93]:
new_data = [[
    # Basic customer info
    1,                  # SeniorCitizen (Yes)
    79.85,              # MonthlyCharges
    4791.0,             # TotalCharges
    1,                  # gender_Male (Yes)
    0,                  # Partner_Yes (No)
    0,                  # Dependents_Yes (No)

    # tenure columns (tenure_2 through tenure_72)
    # Let's say customer has a tenure of 24 months (2 years)
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

    # Services
    1,                  # PhoneService_Yes
    0,                  # MultipleLines_No phone service
    1,                  # MultipleLines_Yes
    1,                  # InternetService_Fiber optic
    0,                  # InternetService_No
    0,                  # OnlineSecurity_No internet service
    0,                  # OnlineSecurity_Yes (means No)
    0,                  # OnlineBackup_No internet service
    1,                  # OnlineBackup_Yes
    0,                  # DeviceProtection_No internet service
    1,                  # DeviceProtection_Yes
    0,                  # TechSupport_No internet service
    0,                  # TechSupport_Yes (means No)
    0,                  # StreamingTV_No internet service
    1,                  # StreamingTV_Yes
    0,                  # StreamingMovies_No internet service
    1,                  # StreamingMovies_Yes

    # Contract and billing
    1,                  # Contract_One year
    0,                  # Contract_Two year (Zero means Month-to-month)
    1,                  # PaperlessBilling_Yes
    0,                  # PaymentMethod_Credit card (automatic)
    1,                  # PaymentMethod_Electronic check
    0,
    1,1,1,0,1
]]

new_data = sc.transform(new_data)
single=knn.predict(new_data)
single

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array(['No'], dtype=object)

In [94]:
single_prob = knn.predict_proba(new_data)
single_prob

array([[0.8, 0.2]])